target:
- transformed_networth
continuous_cols:
- age
- employment_income
- interest_dividend_income
- pension_income
categorical_cols:
- is_female
- race_2
- race_3
- race_4
- race_5
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: regression
head: MixtureDensityHead
head_config:
  num_gaussian: 5
embedding_dims: null
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.mixture_density
_model_name: MDNModel
_backbone_name: Backbone
_config_name: MDNConfig
backbone_config_class: CategoryEmbeddingModelConfig
backbone_config_params:
  task: backbone
  layers: 128-64-32
  activation: ReLU
_probabilistic: true
batch_size: 256
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 200
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: false
track_grad_norm: -1
progress_bar: simple
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 5
enable_checkpointing: true
